#!/bin/sh

# we search for musics on XDG_MUSIC_DIR by default, change below
# for another path
MUSIC_DIR="$XDG_MUSIC_DIR"
CATCHME_SOCKET_PATH="${XDG_CONFIG_HOME:-$HOME/.config}/catchme/catchme-socket"

# --script="$XDG_CONFIG_HOME/mpv/scripts/scripts.disable/autoload.lua" \
pkill -f "mpv.*catchme-socket"
find "$MUSIC_DIR" \( -name "*.mp3" \
	-o -name "*.mkv" \
	-o -name "*.ogg" \
	-o -name "*.flac" \
	-o -name "*.m4a" \
	-o -name "*.opus" \) \
	! -path "sounds" \
	-type f |
	exec mpv --really-quiet \
		--volume=60 \
		--video=no \
		--pause \
		--loop-playlist=inf \
		--term-osd=no \
		--idle=yes \
		--shuffle \
		--load-scripts=no \
		--script="$XDG_CONFIG_HOME/mpv/scripts/scripts.disable/mpv-catchme/" \
		--input-ipc-server="$CATCHME_SOCKET_PATH" \
		--playlist=- >/dev/null 2>&1 &
